"""IA tab (docs/design_ai_layer_transversal.md Sec. 5.1, Sec. 8 step 7): a standalone macro-phase
that CONSUMES data already generated by Fase A/B or uploaded by the user -- never a live control
surface itself (Sec. 5.1's "separar 'control en vivo' de 'análisis'"). Kept out of dashboard.py's
_render_fase_a/_render_fase_b to avoid growing that already-1600+-line file further (Sec. 9's
explicit instruction) -- dashboard.py only adds a landing-page card and a one-line dispatch to
_render_fase_ia() here. Must not import from driveflow.viz.dashboard (that module imports this
one) -- keeps the dependency one-directional.

Shows whichever of {classifier, regressor} the model registry (driveflow.ai.registry, Sec. 7) has
a promoted "pc"-tier run for, per domain -- gracefully saying "not trained yet" for the other
(Sec. 8's own status note: only the vsc_dpc regressor is registered so far, not yet a dc_motor
classifier). No Streamlit import in driveflow.ai.registry or the models/*/builder.py it calls, so
this module is the only place in this file that needs to be a real Streamlit session to run.
"""

import json

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from driveflow.ai.registry import RegistryError, load_promoted_model, resolve
from driveflow.control.dpc.reference import GRID_OMEGA_RAD_S, REFERENCE_MAGNITUDE_V
from driveflow.datagen import Scenario, run_scenario
from driveflow.datagen.runner import _VSC_R_OHM
from driveflow.datagen.scenario import CALIBRATED_MECHANICAL_SEVERITY
from driveflow.models.common.windowing import CANDIDATE_CHANNELS as _DC_MOTOR_CANDIDATE_CHANNELS
from driveflow.models.common.windowing import VSC_DPC_CANDIDATE_CHANNELS as _VSC_DPC_CANDIDATE_CHANNELS
from driveflow.sim.vsc_system import MIN_STABLE_LOAD_RESISTANCE_OHM
from driveflow.viz.dpc_upload_validation import validate_dc_motor_upload, validate_vsc_dpc_forecast_upload

_DOMAIN_LABELS = {"dc_motor": "Fase A -- DC motor diagnosis", "vsc_dpc": "Fase B -- VSC / DPC"}
#: Only tier trained so far (Sec. 8 steps 4/5 scope was the PC tier) -- see design doc status note.
_TIER = "pc"
_PLOT_COLORS = ["#38BDF8", "#34D399", "#FB923C", "#F472B6", "#A78BFA", "#FBBF24"]
#: Same fault vocabulary as dashboard.py's own _BUILTIN_FAULT_TYPES -- duplicated as a literal
#: (not imported) to keep this module's dependency on dashboard.py at zero, per this file's own
#: module docstring; custom fault combinations (dashboard.py's fault manager) are a Fase A sidebar
#: feature, out of scope for this tab's "quick sample, not a live control surface" role.
_BUILTIN_FAULT_TYPES = ["healthy", "outer_race", "inner_race", "ball", "cage"]
#: Fase A's own default speed setpoint (DcPermanentlyExcitedMotor's real nominal ω per GEM's
#: spec, see dashboard.py's card_ref) -- Scenario's own dataclass default (150.0) is NOT this;
#: it's an unrelated placeholder that only dashboard.py's sidebar ever overrides. Sample runs
#: below pass this explicitly instead of leaving omega_ref_rad_s unset, so a "healthy" dc_motor
#: sample matches Fase A's own default operating point rather than silently landing on 150.0.
_DC_MOTOR_DEFAULT_OMEGA_REF_RAD_S = 300.0
#: Which of models.common.windowing's own channel lists validate_dc_motor_upload/
#: validate_vsc_dpc_forecast_upload check an upload against, per domain (see that module's
#: docstring: "at least one of these present" for both, not all-required like the DPC network's
#: own fixed 15-column schema).
_CANDIDATE_CHANNELS_BY_DOMAIN = {"dc_motor": _DC_MOTOR_CANDIDATE_CHANNELS, "vsc_dpc": _VSC_DPC_CANDIDATE_CHANNELS}


def _slider_with_custom(container, label, min_value, max_value, value, step=None, format=None, help=None, key=None):
    """Same pattern as dashboard.py's own helper of the same name (duplicated, not imported --
    this module's docstring forbids depending on dashboard.py): a slider for the common range,
    plus a "Custom value" checkbox that swaps in an unbounded number_input, since a slider alone
    can never go past max_value."""
    base_key = key or label
    slider_val = container.slider(label, min_value, max_value, value, step=step, format=format, help=help, key=f"{base_key}_slider")
    use_custom = container.checkbox("Custom value", key=f"{base_key}_custom", help=f'Type a "{label}" value outside {min_value}-{max_value} above.')
    if not use_custom:
        return slider_val
    is_int = isinstance(value, int) and not isinstance(value, bool)
    custom_val = container.number_input(
        f"{label} (custom)",
        value=int(slider_val) if is_int else float(slider_val),
        step=step or (1 if is_int else 0.1),
        format=format,
        key=f"{base_key}_custom_input",
    )
    return int(custom_val) if is_int else custom_val


@st.cache_resource
def _cached_promoted_model(domain: str, tier: str, block: str):
    """Same cache_resource pattern as dashboard.py's _load_dpc_model -- rebuilding the keras
    model graph and reloading weights on every widget interaction would be wasteful; RegistryError
    (nothing promoted yet) is deliberately NOT cached here, so a later promotion is picked up on
    the next call rather than staying stuck at "not registered" for the rest of the session."""
    return load_promoted_model(domain, tier, block)


def _generate_sample_dataframe(domain: str, **scenario_kwargs) -> pd.DataFrame:
    """A short simulation run for the chosen domain, as a quick "try it without a file" data
    source -- same simulation engine Fase A/B already use, not a new one. scenario_kwargs come
    from the sidebar widgets _render_fase_ia builds below (fault/severity for dc_motor,
    load/reference for vsc_dpc), so this is a real (if narrower than Fase A/B's own sidebar)
    scenario, not a single hardcoded run."""
    if domain == "dc_motor":
        records = run_scenario(Scenario(scenario_id="ai_tab_sample_dc", **scenario_kwargs))
    else:
        records = run_scenario(Scenario(scenario_id="ai_tab_sample_vsc", controller_type="DPC", plant_config_id="vsc_dpc_v1", **scenario_kwargs))
    return pd.DataFrame.from_records(records)


def _channel_upload_template_df(domain: str, n_rows: int = 5) -> pd.DataFrame:
    """A genuine, physically-consistent example for the "Upload a file" format help below --
    a short real Scenario run for `domain` (same principle as dashboard.py's own
    _dpc_upload_template_df for the DPC network's upload tab), not hand-typed placeholder
    numbers. Only channels that this particular run actually populated (dc_motor's
    current_s/current_t stay NaN in the single-phase model this platform simulates -- see
    runner.py -- and a template column that's all-NaN would make the file it's IN fail
    validate_dc_motor_upload's own "no valid rows left" check, which is the opposite of helpful
    for an example file)."""
    channels = _CANDIDATE_CHANNELS_BY_DOMAIN[domain]
    df = _generate_sample_dataframe(domain, duration_s=0.05, seed=0)
    usable = [c for c in channels if c in df.columns and df[c].notna().all()]
    return df[usable].head(n_rows).reset_index(drop=True)


def _render_upload_format_help(domain: str):
    """Sec. "no especifica el formato o un ejemplo" -- same "Required format" expander + example
    download pattern as Fase B's own DPC upload tab (dashboard.py's _render_dpc_upload_eval), but
    for validate_dc_motor_upload/validate_vsc_dpc_forecast_upload's own "at least one known
    channel" schema (see _CANDIDATE_CHANNELS_BY_DOMAIN's comment) instead of the DPC network's
    fixed 15-column one."""
    channels = _CANDIDATE_CHANNELS_BY_DOMAIN[domain]
    with st.sidebar.expander("Required format", expanded=False):
        st.caption(f"At least one of these {len(channels)} column(s) must be present (any of them, not all): `{'`, `'.join(channels)}`.")
        st.caption(
            "CSV: a header row with these column names (any order -- matched by name, not "
            "position). JSON: a list of objects with these keys, or an object of equal-length "
            "arrays keyed by these names. Extra columns are ignored. Rows do NOT need to be a "
            "time series -- the model windows over the LAST rows in the file, in file order."
        )
        template_df = _channel_upload_template_df(domain)
        col_csv, col_json = st.columns(2)
        col_csv.download_button(
            "Example (CSV)", template_df.to_csv(index=False),
            file_name=f"ia_{domain}_example.csv", key=f"ia_template_csv_{domain}",
        )
        col_json.download_button(
            "Example (JSON)", template_df.to_json(orient="records", indent=2),
            file_name=f"ia_{domain}_example.json", key=f"ia_template_json_{domain}",
        )


def _sample_run_controls(domain: str) -> dict:
    """Sidebar widgets for the "Generate a sample run" data source -- a deliberately narrower
    subset of Fase A/B's own scenario sidebar (no motor-characteristic overrides, no custom fault
    combinations): enough to exercise the model on something other than one fixed default run,
    without duplicating the full A/B control surface this tab is explicitly not supposed to be
    (Sec. 5.1). Every numeric control uses _slider_with_custom, same as Fase A/B, so nothing here
    is capped below what a Scenario itself accepts."""
    duration_s = _slider_with_custom(st.sidebar, "Duration (s)", 0.05, 1.0, 0.3, key="ia_duration")
    seed = st.sidebar.number_input("Seed", value=0, step=1, key="ia_seed")
    kwargs = {"duration_s": duration_s, "seed": int(seed)}

    if domain == "dc_motor":
        fault_label = st.sidebar.selectbox("Fault type", _BUILTIN_FAULT_TYPES, key="ia_fault_type")
        fault_type = None if fault_label == "healthy" else fault_label
        kwargs["fault_type"] = fault_type
        # Explicit, not Scenario's own dataclass default (150.0) -- see
        # _DC_MOTOR_DEFAULT_OMEGA_REF_RAD_S's own comment above.
        kwargs["omega_ref_rad_s"] = _slider_with_custom(
            st.sidebar, "Speed setpoint ω_ref (rad/s)", 10.0, 350.0, _DC_MOTOR_DEFAULT_OMEGA_REF_RAD_S, key="ia_omega_ref"
        )
        if fault_type is not None:
            kwargs["electrical_severity"] = _slider_with_custom(st.sidebar, "Electrical severity (Nm)", 0.0, 20.0, 8.0, key="ia_elec_severity")
            default_mech = float(CALIBRATED_MECHANICAL_SEVERITY.get(fault_type, 0.0))
            kwargs["mechanical_severity"] = _slider_with_custom(
                st.sidebar, "Mechanical severity", 0.0, 0.2, default_mech, format="%.3f", key="ia_mech_severity"
            )
    else:
        load_resistance_ohm = _slider_with_custom(
            st.sidebar,
            "Load resistance R (Ω)",
            MIN_STABLE_LOAD_RESISTANCE_OHM,
            20.0,
            float(_VSC_R_OHM),
            format="%.4f",
            key="ia_load_r",
            help=f"Floored at {MIN_STABLE_LOAD_RESISTANCE_OHM:.2f}Ω, the plant's own open-loop stability limit (Fase B sidebar has the full explanation) -- below it the closed loop is expected to diverge regardless of the controller. Use 'Custom value' to go below it on purpose.",
        )
        kwargs["load_resistance_ohm"] = load_resistance_ohm
        kwargs["reference_magnitude_v"] = _slider_with_custom(st.sidebar, "Reference magnitude |v_ref| (V)", 10.0, 150.0, float(REFERENCE_MAGNITUDE_V), key="ia_ref_mag")
        kwargs["reference_omega_rad_s"] = _slider_with_custom(
            st.sidebar, "Reference frequency ω (rad/s)", 50.0, 700.0, float(GRID_OMEGA_RAD_S), format="%.2f", key="ia_ref_omega"
        )
    return kwargs


def _normalize_window(window: np.ndarray) -> tuple:
    mu, sigma = window.mean(axis=0), window.std(axis=0)
    sigma = np.where(sigma > 1e-6, sigma, 1.0)
    return (window - mu) / sigma, mu, sigma


def _select_last_window(df: pd.DataFrame, channels: list, input_window: int):
    missing = [c for c in channels if c not in df.columns or df[c].isna().all()]
    if missing:
        st.warning(f"Missing channel(s) this model needs: {', '.join(missing)} -- can't evaluate.")
        return None
    if len(df) < input_window:
        st.warning(f"Need at least {input_window} rows to fill one window -- only {len(df)} available.")
        return None
    return df[channels].iloc[-input_window:].to_numpy(dtype=np.float32)


#: The two tiers that get distilled from the PC-tier teacher and exported to TFLite (Sec. 8 step
#: 8) -- "pc" itself runs the native keras.Model directly, no .tflite to download for it.
_EDGE_TIERS = ["rpi5", "esp32"]
_EDGE_TIER_LABELS = {"rpi5": "Raspberry Pi 5 (TFLite float16)", "esp32": "ESP32 (TFLite int8)"}


def _render_edge_deployment(domain: str):
    """The gap this closes: Sec. 8 step 8's real, distilled+exported .tflite artifacts sit on
    disk (configs/{classifiers,regressors}/<tier config>/<run>/model.tflite) but nothing in this
    tab ever surfaced them -- a user could evaluate the PC-tier model here, but had no way to
    actually get the Raspberry Pi 5/ESP32 files to put on real hardware. Always rendered
    (independent of the "generate a sample run"/"upload a file" choice below) -- downloading the
    model doesn't need any evaluation data first."""
    with st.expander("📦 Download for edge deployment (Raspberry Pi 5 / ESP32)", expanded=False):
        any_available = False
        for block in ("classifier", "regressor"):
            for tier in _EDGE_TIERS:
                try:
                    run_dir = resolve(domain, tier, block)
                except RegistryError:
                    continue
                tflite_path = run_dir / "model.tflite"
                if not tflite_path.exists():
                    st.caption(f"{block.capitalize()} — {_EDGE_TIER_LABELS[tier]}: promoted, but not exported to TFLite yet.")
                    continue
                any_available = True
                with (run_dir / "metrics.json").open() as f:
                    metrics = json.load(f)
                headline = f"test accuracy {metrics['test_accuracy']:.1%}" if "test_accuracy" in metrics else f"test RMSE {metrics['test_rmse']:.3f} (normalized)"
                tflite_bytes = tflite_path.read_bytes()
                col_dl, col_info = st.columns([2, 3])
                col_dl.download_button(
                    f"{block.capitalize()} — {_EDGE_TIER_LABELS[tier]}",
                    tflite_bytes,
                    file_name=f"{domain}_{tier}_{block}.tflite",
                    key=f"ia_edge_dl_{domain}_{tier}_{block}",
                )
                col_info.caption(f"{len(tflite_bytes) / 1024:.1f} KB · {headline} · distilled from the promoted PC-tier run ({run_dir.name})")
        if not any_available:
            st.caption(f"Nothing promoted and exported to TFLite yet for {_DOMAIN_LABELS[domain]} at the rpi5/esp32 tiers.")


def _render_classifier_panel(domain: str, df: pd.DataFrame):
    st.markdown("##### Classifier")
    try:
        model, config, metrics = _cached_promoted_model(domain, _TIER, "classifier")
    except RegistryError:
        st.info(f"No classifier is registered yet for {_DOMAIN_LABELS[domain]} (docs/design_ai_layer_transversal.md Sec. 8 step 6).")
        return

    channels = metrics["channels"]
    window = _select_last_window(df, channels, config.input_window)
    if window is None:
        return
    window_n, _, _ = _normalize_window(window)

    probs = model(window_n[np.newaxis, ...], training=False).numpy()[0]
    classes = metrics["classes"]
    pred_idx = int(np.argmax(probs))

    st.metric("Predicted class", classes[pred_idx], f"{probs[pred_idx] * 100:.1f}% confidence")
    st.bar_chart(pd.Series(probs, index=classes, name="probability"))
    st.caption(f"Tier: {config.tier}. Channels: {', '.join(channels)}. Test accuracy at training time: {metrics.get('test_accuracy')}.")


def _render_regressor_panel(domain: str, df: pd.DataFrame):
    st.markdown("##### Regressor (forecaster)")
    try:
        model, config, metrics = _cached_promoted_model(domain, _TIER, "regressor")
    except RegistryError:
        st.info(f"No regressor is registered yet for {_DOMAIN_LABELS[domain]} (docs/design_ai_layer_transversal.md Sec. 8 step 6).")
        return

    channels = metrics["channels"]
    window = _select_last_window(df, channels, config.input_window)
    if window is None:
        return
    window_n, mu, sigma = _normalize_window(window)

    forecast_n = model(window_n[np.newaxis, ...], training=False).numpy()[0]
    forecast = forecast_n * sigma + mu  # de-normalize back to physical units

    fig = go.Figure()
    for i, ch in enumerate(channels):
        fig.add_trace(go.Scatter(y=forecast[:, i], name=ch, mode="lines", line=dict(color=_PLOT_COLORS[i % len(_PLOT_COLORS)])))
    fig.update_layout(
        height=340, margin=dict(l=10, r=10, t=30, b=10),
        xaxis_title="forecast step", yaxis_title="value",
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        legend=dict(orientation="h", y=1.1),
    )
    st.plotly_chart(fig, width="stretch")
    st.caption(f"Tier: {config.tier}. Horizon: {config.horizon} steps. Test RMSE (normalized) at training time: {metrics.get('test_rmse')}.")


def _empty_state_ia():
    st.info("Choose a data source in the sidebar to get started -- generate a short sample run, or upload a file.")


def _render_fase_ia():
    st.sidebar.markdown(
        '<div class="df-sidebar-title">IA</div>'
        '<div class="df-sidebar-hint">Consumes data already generated by Fase A/B, or an upload -- never a live control surface</div>',
        unsafe_allow_html=True,
    )
    domain = st.sidebar.selectbox("Domain", list(_DOMAIN_LABELS), format_func=lambda d: _DOMAIN_LABELS[d], key="ia_domain")

    _render_edge_deployment(domain)

    source = st.sidebar.radio("Data source", ["Generate a sample run", "Upload a file"], key="ia_source")

    df = None
    if source == "Generate a sample run":
        scenario_kwargs = _sample_run_controls(domain)
        if st.sidebar.button("Generate", type="primary", key="ia_generate"):
            with st.spinner("Simulating..."):
                st.session_state["ia_df"] = _generate_sample_dataframe(domain, **scenario_kwargs)
                st.session_state["ia_df_domain"] = domain
                st.session_state["ia_df_config"] = scenario_kwargs
        if st.session_state.get("ia_df_domain") == domain:
            df = st.session_state.get("ia_df")
            if df is not None and st.session_state.get("ia_df_config") != scenario_kwargs:
                st.sidebar.caption("⚠ Parameters changed since this run -- click Generate to refresh.")
        if df is None:
            _empty_state_ia()
            return
    else:
        _render_upload_format_help(domain)
        uploaded = st.sidebar.file_uploader("Upload dataset", type=["csv", "json"], key="ia_upload")
        if uploaded is None:
            _empty_state_ia()
            return
        try:
            df_raw = pd.read_json(uploaded) if uploaded.name.lower().endswith(".json") else pd.read_csv(uploaded)
        except Exception as e:
            st.error(f"Could not parse '{uploaded.name}': {e}")
            return
        validator = validate_dc_motor_upload if domain == "dc_motor" else validate_vsc_dpc_forecast_upload
        df, _, messages = validator(df_raw)
        for level, text in messages:
            getattr(st, level)(text)
        if df is None:
            return

    st.caption(f"{len(df)} row(s) available for evaluation.")
    col1, col2 = st.columns(2)
    with col1:
        _render_classifier_panel(domain, df)
    with col2:
        _render_regressor_panel(domain, df)
