"""IA tab (docs/design_ai_layer_transversal.md Sec. 5.1, Sec. 8 step 7): a standalone macro-phase
that CONSUMES data already generated by Fase A/B or uploaded by the user -- never a live control
surface itself (Sec. 5.1's "separar 'control en vivo' de 'análisis'"). Kept out of dashboard.py's
_render_fase_a/_render_fase_b to avoid growing that already-1600+-line file further (Sec. 9's
explicit instruction) -- dashboard.py only adds a landing-page card and a one-line dispatch to
_render_fase_ia() here. Must not import from driveflow.viz.dashboard (that module imports this
one) -- keeps the dependency one-directional.

Shows whichever of {classifier, regressor} the model registry (driveflow.ai.registry, Sec. 7) has
a promoted "pc"-tier run for, per domain -- gracefully saying "not trained yet" for the other
(Sec. 8's own status note: only the vsc_dpc regressor is registered so far, not yet a dc_motor
classifier). No Streamlit import in driveflow.ai.registry or the models/*/builder.py it calls, so
this module is the only place in this file that needs to be a real Streamlit session to run.
"""

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from driveflow.ai.registry import RegistryError, load_promoted_model
from driveflow.datagen import Scenario, run_scenario
from driveflow.viz.dpc_upload_validation import validate_dc_motor_upload, validate_vsc_dpc_forecast_upload

_DOMAIN_LABELS = {"dc_motor": "Fase A -- DC motor diagnosis", "vsc_dpc": "Fase B -- VSC / DPC"}
#: Only tier trained so far (Sec. 8 steps 4/5 scope was the PC tier) -- see design doc status note.
_TIER = "pc"
_PLOT_COLORS = ["#38BDF8", "#34D399", "#FB923C", "#F472B6", "#A78BFA", "#FBBF24"]


@st.cache_resource
def _cached_promoted_model(domain: str, tier: str, block: str):
    """Same cache_resource pattern as dashboard.py's _load_dpc_model -- rebuilding the keras
    model graph and reloading weights on every widget interaction would be wasteful; RegistryError
    (nothing promoted yet) is deliberately NOT cached here, so a later promotion is picked up on
    the next call rather than staying stuck at "not registered" for the rest of the session."""
    return load_promoted_model(domain, tier, block)


def _generate_sample_dataframe(domain: str) -> pd.DataFrame:
    """A short default simulation run for the chosen domain, purely as a quick "try it without a
    file" data source -- same simulation engine Fase A/B already use, not a new one."""
    if domain == "dc_motor":
        records = run_scenario(Scenario(scenario_id="ai_tab_sample_dc", duration_s=0.3))
    else:
        records = run_scenario(Scenario(scenario_id="ai_tab_sample_vsc", controller_type="DPC", plant_config_id="vsc_dpc_v1", duration_s=0.3))
    return pd.DataFrame.from_records(records)


def _normalize_window(window: np.ndarray) -> tuple:
    mu, sigma = window.mean(axis=0), window.std(axis=0)
    sigma = np.where(sigma > 1e-6, sigma, 1.0)
    return (window - mu) / sigma, mu, sigma


def _select_last_window(df: pd.DataFrame, channels: list, input_window: int):
    missing = [c for c in channels if c not in df.columns or df[c].isna().all()]
    if missing:
        st.warning(f"Missing channel(s) this model needs: {', '.join(missing)} -- can't evaluate.")
        return None
    if len(df) < input_window:
        st.warning(f"Need at least {input_window} rows to fill one window -- only {len(df)} available.")
        return None
    return df[channels].iloc[-input_window:].to_numpy(dtype=np.float32)


def _render_classifier_panel(domain: str, df: pd.DataFrame):
    st.markdown("##### Classifier")
    try:
        model, config, metrics = _cached_promoted_model(domain, _TIER, "classifier")
    except RegistryError:
        st.info(f"No classifier is registered yet for {_DOMAIN_LABELS[domain]} (docs/design_ai_layer_transversal.md Sec. 8 step 6).")
        return

    channels = metrics["channels"]
    window = _select_last_window(df, channels, config.input_window)
    if window is None:
        return
    window_n, _, _ = _normalize_window(window)

    probs = model(window_n[np.newaxis, ...], training=False).numpy()[0]
    classes = metrics["classes"]
    pred_idx = int(np.argmax(probs))

    st.metric("Predicted class", classes[pred_idx], f"{probs[pred_idx] * 100:.1f}% confidence")
    st.bar_chart(pd.Series(probs, index=classes, name="probability"))
    st.caption(f"Tier: {config.tier}. Channels: {', '.join(channels)}. Test accuracy at training time: {metrics.get('test_accuracy')}.")


def _render_regressor_panel(domain: str, df: pd.DataFrame):
    st.markdown("##### Regressor (forecaster)")
    try:
        model, config, metrics = _cached_promoted_model(domain, _TIER, "regressor")
    except RegistryError:
        st.info(f"No regressor is registered yet for {_DOMAIN_LABELS[domain]} (docs/design_ai_layer_transversal.md Sec. 8 step 6).")
        return

    channels = metrics["channels"]
    window = _select_last_window(df, channels, config.input_window)
    if window is None:
        return
    window_n, mu, sigma = _normalize_window(window)

    forecast_n = model(window_n[np.newaxis, ...], training=False).numpy()[0]
    forecast = forecast_n * sigma + mu  # de-normalize back to physical units

    fig = go.Figure()
    for i, ch in enumerate(channels):
        fig.add_trace(go.Scatter(y=forecast[:, i], name=ch, mode="lines", line=dict(color=_PLOT_COLORS[i % len(_PLOT_COLORS)])))
    fig.update_layout(
        height=340, margin=dict(l=10, r=10, t=30, b=10),
        xaxis_title="forecast step", yaxis_title="value",
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        legend=dict(orientation="h", y=1.1),
    )
    st.plotly_chart(fig, width="stretch")
    st.caption(f"Tier: {config.tier}. Horizon: {config.horizon} steps. Test RMSE (normalized) at training time: {metrics.get('test_rmse')}.")


def _empty_state_ia():
    st.info("Choose a data source in the sidebar to get started -- generate a short sample run, or upload a file.")


def _render_fase_ia():
    st.sidebar.markdown(
        '<div class="df-sidebar-title">IA</div>'
        '<div class="df-sidebar-hint">Consumes data already generated by Fase A/B, or an upload -- never a live control surface</div>',
        unsafe_allow_html=True,
    )
    domain = st.sidebar.selectbox("Domain", list(_DOMAIN_LABELS), format_func=lambda d: _DOMAIN_LABELS[d], key="ia_domain")
    source = st.sidebar.radio("Data source", ["Generate a sample run", "Upload a file"], key="ia_source")

    df = None
    if source == "Generate a sample run":
        if st.sidebar.button("Generate", type="primary", key="ia_generate"):
            with st.spinner("Simulating..."):
                st.session_state["ia_df"] = _generate_sample_dataframe(domain)
                st.session_state["ia_df_domain"] = domain
        if st.session_state.get("ia_df_domain") == domain:
            df = st.session_state.get("ia_df")
        if df is None:
            _empty_state_ia()
            return
    else:
        uploaded = st.sidebar.file_uploader("Upload dataset", type=["csv", "json"], key="ia_upload")
        if uploaded is None:
            _empty_state_ia()
            return
        try:
            df_raw = pd.read_json(uploaded) if uploaded.name.lower().endswith(".json") else pd.read_csv(uploaded)
        except Exception as e:
            st.error(f"Could not parse '{uploaded.name}': {e}")
            return
        validator = validate_dc_motor_upload if domain == "dc_motor" else validate_vsc_dpc_forecast_upload
        df, _, messages = validator(df_raw)
        for level, text in messages:
            getattr(st, level)(text)
        if df is None:
            return

    st.caption(f"{len(df)} row(s) available for evaluation.")
    col1, col2 = st.columns(2)
    with col1:
        _render_classifier_panel(domain, df)
    with col2:
        _render_regressor_panel(domain, df)
